####################################
## ssgsea parameters 
panoply_ssgsea: 
 nperm: 1000
 weight: 0.75
 output_prefix: "ssgsea-results"
 sample_norm_type: "rank"        ## rank, log, log.rank, none
 correl_type: "z.score"          ## "rank", "z.score", "symm.rank"
 statistic: "area.under.RES"     ## "area.under.RES", "Kolmogorov-Smirnov" 
 output_score_type: "NES"        ## 'Score type: "ES" - enrichment score,  "NES" - normalized ES'
 min_overlap: 10                 ## 'Minimal overlap between signature and data set.'
 extended_output: TRUE           ## 'If TRUE additional stats on signature coverage etc. will be included as row annotations in the GCT results files.'
 export_signat_gct: TRUE         ## For each signature export expression GCT files.
 global_fdr: FALSE               ## If TRUE global FDR across all data columns is calculated.
 multi_core: TRUE                ## If TRUE processing will be parallized across gene sets using (N-1) CPU cores.
